# Configuration options that are shared across all environments
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

local: &local
  <<: *default
  username: <%= ENV.key?("DATABASE_URL") ? URI(ENV.fetch("DATABASE_URL")).user : "" %>
  password: <%= ENV.key?("DATABASE_URL") ? URI(ENV.fetch("DATABASE_URL")).password : "" %>
  host: <%= ENV.key?("DATABASE_URL") ? URI(ENV.fetch("DATABASE_URL")).host : "" %>
  port: <%= ENV.key?("DATABASE_URL") ? URI(ENV.fetch("DATABASE_URL")).port : "" %>

# Development config
development:
  <<: *local
  database: project_name_snake_development

# Test config
test:
  <<: *local
  database: project_name_snake_test

# Staging/Production config
production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
